name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject environment variable names
        run: |
          sed -i "s|SPOTIFY_CLIENT_ID|${{ secrets.SPOTIFY_CLIENT_ID }}|g" src/script.js
          sed -i "s|TM_CLIENT_ID|${{ secrets.TM_CLIENT_ID }}|g" src/script.js

      - name: Print secret keys (for debugging)
        run: |
          echo "SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}"
          echo "TM_CLIENT_ID: ${{ secrets.TM_CLIENT_ID }}"

      - name: List secrets (for debugging)
        run: |
          echo "Available secrets:"
          printenv | grep -E '^SPOTIFY_CLIENT_ID=|^TM_CLIENT_ID=|^GITHUB_TOKEN='
        

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy using SPOTIFY_CLIENT_ID (custom deployment command)
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        run: npm run dev

      - name: Deploy using TM_CLIENT_ID (custom deployment command)
        env:
          TM_CLIENT_ID: ${{ secrets.TM_CLIENT_ID }}
        run: npm run dev
