name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TM_CLIENT_ID=${{ secrets.TM_CLIENT_ID }}" >> $GITHUB_ENV

      - name: Inject environment variable names
        run: |
          sed -i "s|SPOTIFY_CLIENT_ID|${SPOTIFY_CLIENT_ID}|g" src/script.js
          sed -i "s|TM_CLIENT_ID|${TM_CLIENT_ID}|g" src/script.js

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
